### ISSUE TITLE
not an issue

### ISSUE THREAD

**Issue by johndpope** [zhanglonghao1992/One-Shot_Free-View_Neural_Talking_Head_Synthesis#1]
it's just creating from a single photo? not like fsgan by @YuvalNirkin ? 
https://github.com/YuvalNirkin/fsgan

**Comment by zhanglonghao1992** [comment]
> it's just creating from a single photo? not like fsgan by @YuvalNirkin ?
> https://github.com/YuvalNirkin/fsgan

Yes, just need a single source image and a driving video.
