### ISSUE TITLE
请问下训练的配置

### ISSUE THREAD

**Issue by highway007** [zhanglonghao1992/One-Shot_Free-View_Neural_Talking_Head_Synthesis#10]
请问下大佬训练用的gpu是什么配置的啊？训练速度大概是多少？

**Comment by zhanglonghao1992** [comment]
A-100 GPU x 8.
1 epoch = 1 hour.

**Comment by highway007** [comment]
thanks！

**Comment by vinayak015** [comment]
Could you tell approximately how many epochs were required for training? @zhanglonghao1992

**Comment by zhanglonghao1992** [comment]
> Could you tell approximately how many epochs were required for training? @zhanglonghao1992

About 120 epochs
