### ISSUE TITLE
Compressing the features

### ISSUE THREAD

**Issue by vinayak015** [zhanglonghao1992/One-Shot_Free-View_Neural_Talking_Head_Synthesis#12]
Before creating sparse motion (in dense_motion.py), any reason to use 1x1 conv?

**Comment by zhanglonghao1992** [comment]
@vinayak015 You mean the "compress" right? Here is the explanation of the original author of the paper： https://github.com/NVlabs/face-vid2vid/issues/2#issuecomment-865950115

**Comment by vinayak015** [comment]
Thank you for replying. I will ask more if required. And it's a nice work :)
