### ISSUE TITLE
share log.txt

### ISSUE THREAD

**Issue by romanvey** [zhanglonghao1992/One-Shot_Free-View_Neural_Talking_Head_Synthesis#14]
@zhanglonghao1992 could you provide your log.txt from your training? I think it would be beneficial for people to understand are they going in the right direction or not.

**Comment by Vijayue** [comment]
ye! I hope so, the training process is really hard. 😢😢

**Comment by zhanglonghao1992** [comment]
@romanvey @Vijayue I'll release the checkpoint and the training log file (if I can still find it - -!).

**Comment by romanvey** [comment]
Thank you!
