### ISSUE TITLE
ValueError: Could not find a format to write the specified file in mode 'I'

### ISSUE THREAD

**Issue by laleh-samadfam** [zhanglonghao1992/One-Shot_Free-View_Neural_Talking_Head_Synthesis#18]
Thank you for your hard work. 

I am trying to run demo.py and I keep getting this error. Is there any thing I'm missing for running the code?
I use an .mp4 video as a driving video, the code runs till the end, I have a list of prediction frames, but can not write the final video.

**Comment by 307509256** [comment]
@laleh-samadfam  choosing a saving file format for mimsave？  what format ？
