### ISSUE TITLE
Early training behavior

### ISSUE THREAD

**Issue by GLivshits** [zhanglonghao1992/One-Shot_Free-View_Neural_Talking_Head_Synthesis#23]
Hi. First of all, thanks for your code.
I'm training the model from scratch. I've found out that images from the generator look similar to the source image, but not the driving (pose, emotion, and so on). Perhaps, I'm at the start of training (only a single epoch has passed).
Is this behavior expected?
Please find the log image attached.
![Images_epoch_0_iteration_2000_rec jpg_00000000](https://user-images.githubusercontent.com/47557983/139105366-85d0c82f-20e1-4670-9570-9b45561c3c44.jpeg)

**Comment by chenzhekl** [comment]
I observed something similar, which lasted for quite a long time in the early stage of training (already ~2 days on 2 RTX6000). This is interesting, as the loss terms only encourage the reconstruction to stay close to the driving image. Do you have any idea why this is the case?
