### ISSUE TITLE
headpose error

### ISSUE THREAD

**Issue by highway007** [zhanglonghao1992/One-Shot_Free-View_Neural_Talking_Head_Synthesis#29]
here is the result when I set headpose_pred_to_degree() return to 0: 
https://user-images.githubusercontent.com/46595349/142132076-dd5cffc6-fa64-4c64-9f01-63d649137db8.mp4
and here is the original result:
https://user-images.githubusercontent.com/46595349/142132085-b4707739-c2e0-4bf1-91fb-be4f318cb775.mp4
seems headpose-pred do not work correctly.
ps : here is the ori-video and pic

https://user-images.githubusercontent.com/46595349/142132892-a1c39ba6-9546-4eba-bf27-bcb120260c40.mp4
![ouy2](https://user-images.githubusercontent.com/46595349/142132989-138da59a-93d9-4c5e-a584-4f0dba18b576.jpg)

**Comment by zhanglonghao1992** [comment]
@highway007 
Make sure that the following functions in demo.py and animate.py belong to the beta version：
get_rotation_matrix()
keypoint_transformation()
normalize_kp()

https://github.com/zhanglonghao1992/One-Shot_Free-View_Neural_Talking_Head_Synthesis/issues/8#issuecomment-963928565

**Comment by highway007** [comment]
It works! Use keypoint_transformation and get_rotation_matrix all beta version.
Thanks
