### ISSUE TITLE
About rotationt replacing the Jacobians

### ISSUE THREAD

**Issue by begins233** [zhanglonghao1992/One-Shot_Free-View_Neural_Talking_Head_Synthesis#3]
Very good result.
When I tried to reproduce this paper, I found that the Jacobian matrix was cancelled in the [v3 version of arxiv.](https://arxiv.org/pdf/2011.15126.pdf) I canceled the Jacobians and got very worried results. I would like to ask if you use the Rotation parameter to replace the Jacobian. Also want to know if the code will be open source in the near future?

**Comment by zhanglonghao1992** [comment]
@begins233 I'm trying training without the Jacobians. It looks fine so far.

**Comment by begins233** [comment]
@zhanglonghao1992  Thanks.
There may be some bugs in my code, I will check the code again. This is my current result. The left is the output, the middle is the output with no expression coefficients, and the right is GT. Have you ever encountered such a situation where the posture is correct but the face is expressionless, I hope you can give me some suggestions, thank you.

https://user-images.githubusercontent.com/24779371/125877738-74d08d30-103d-4f16-88f4-bdd2b0d692c5.mp4

**Comment by zhanglonghao1992** [comment]
@begins233 It looks like there's something wrong with your implementation.

**Comment by begins233** [comment]
> @begins233 It looks like there's something wrong with your implementation.

Thank you, I try to keep checking my code. Hope you can open source as soon as possible.
