### ISSUE TITLE
Does quantitative evaluation results match the ones in the original paper?

### ISSUE THREAD

**Issue by lostork** [zhanglonghao1992/One-Shot_Free-View_Neural_Talking_Head_Synthesis#36]
Thank you so much for your implementation. 
I wonder whether you have quantitatively evaluated your implementation and compare your results with ones in original paper.

Have you calculated L1, PNSR, MS-SSIM scores?

**Comment by zhanglonghao1992** [comment]
@lostork To be honest, I don't care much about these scores. I think the generation algorithms based on GANs should be evaluated mainly through observation. Of course, except for publishing papers :)
