### ISSUE TITLE
训练时间问题

### ISSUE THREAD

**Issue by wuchaoml** [zhanglonghao1992/One-Shot_Free-View_Neural_Talking_Head_Synthesis#37]
您好，想咨询一下，我们用4张v100，每个batch size设置为16，repeate设置为1的时候，每个epoch都要一个小时左右，如果repate设为75每个epoch都要75个小时了，这可能是什么原因啊，谢谢

**Comment by zhanglonghao1992** [comment]
@wuchaoml repeate75相当于在一个id（或sample）里要随机取75对frame训练，当然时间上就是大约75倍了

**Comment by wuchaoml** [comment]
> zhanglonghao1992
嗯嗯，但我记得您在某个问题下回答您的一个epoch大概一个小时，可以请教一下您的设备配置吗？以及您repeat和batch size设置的分别是多少啊，因为我现在repeat为1，batch size16， 4张v100，每个epoch也需要一个小时，感觉时间太长了，谢谢

**Comment by wuchaoml** [comment]
> @wuchaoml repeate75相当于在一个id（或sample）里要随机取75对frame训练，当然时间上就是大约75倍了
嗯嗯，但我记得您在某个问题下回答您的一个epoch大概一个小时，可以请教一下您的设备配置吗？以及您repeat和batch size设置的分别是多少啊，因为我现在repeat为1，batch size16， 4张v100，每个epoch也需要一个小时，感觉时间太长了，谢谢

**Comment by zhanglonghao1992** [comment]
@wuchaoml 一个小时是训练beta版本，generator比较小，现在gererator加入了spade block。当然为了节约缓存和训练/推理时间，你可以只用3个spade block。
另外我的训练配置是8卡A100，供你参考。

**Comment by wuchaoml** [comment]
> @wuchaoml 一个小时是训练beta版本，generator比较小，现在gererator加入了spade block。当然为了节约缓存和训练/推理时间，你可以只用3个spade block。 另外我的训练配置是8卡A100，供你参考。

好的好的，我尝试一下，谢谢大佬的回复
