### ISSUE TITLE
请问这个模型 在头部转动的压力测试下表现怎么样

### ISSUE THREAD

**Issue by madgnot** [zhanglonghao1992/One-Shot_Free-View_Neural_Talking_Head_Synthesis#38]
现在给出的结果头部姿态都运动不是很大，当头部姿态运动较大的情况下，这个模型的结果怎么样？

**Comment by zhanglonghao1992** [comment]
@madgnot 训练集里其实并没有很多大姿态的sample，所以模型处理大姿态效果较差。NV不release数据集，只能在Vox-Celeb上训

**Comment by madgnot** [comment]
请问你展示的结果都是微调过的吗？还是本身在训练集里面就训练过？

**Comment by zhanglonghao1992** [comment]
@madgnot 没有微调过，也不在训练集里

**Comment by madgnot** [comment]
这个模型的泛化能力这么强吗？不微调就可以生成这些头部运动

**Comment by zhanglonghao1992** [comment]
@madgnot  Yep.

**Comment by madgnot** [comment]
请问你这个在八卡A100 的情况下训练了多久

**Comment by zhanglonghao1992** [comment]
> 请问你这个在八卡A100 的情况下训练了多久

几天
