### ISSUE TITLE
Quality drop when using absolute motion transfer

### ISSUE THREAD

**Issue by laleh-samadfam** [zhanglonghao1992/One-Shot_Free-View_Neural_Talking_Head_Synthesis#56]
Hello, 
 
When not using "relative" flag in demo, the generated video's quality highly drops. Have you been able to generate reasonable videos with absolute motion transfer?

Thanks

**Comment by zhanglonghao1992** [comment]
@laleh-samadfam Hi there. The "relative motion" is the key of this method due to its training mechanism. Only when the postures of the source face and the driving face are similar, generation results with the "absolute motion" are good.
