### ISSUE TITLE
关于重新训练的问题？

### ISSUE THREAD

**Issue by DWCTOD** [zhanglonghao1992/One-Shot_Free-View_Neural_Talking_Head_Synthesis#6]
您好，
感谢大佬的分享。遇到一些问题想请教一下。
首先数据集的处理，参考：https://github.com/AliaksandrSiarohin/video-preprocessing 
由于数据集比较大，我这边尝试先用少量数据集试试能不能跑起来。（处理好的数据集放在一个文件夹下，分成train 和test）
同时需要补充hopenet的权重文件：https://github.com/natanielruiz/deep-head-pose
这样子处理之后，没有报错，但是会一直卡在
Loading hopenet...

**Comment by zhanglonghao1992** [comment]
@DWCTOD 确定是卡在loading hopenet吗，正常应该不会卡在这的，你再给多一些debug细节吧

**Comment by DWCTOD** [comment]
> @DWCTOD 确定是卡在loading hopenet吗，正常应该不会卡在这的，你再给多一些debug细节吧

谢谢大佬回复，好像是我的多卡计算资源不够导致的，不报错，但是会卡在那里（Loading hopenet 下面训练的部分）

**Comment by zhangyahu1** [comment]
@DWCTOD  请问怎么处理的VoxCeleb2数据集呢？
