### ISSUE TITLE
How did you train head pose estimator H and delta?

### ISSUE THREAD

**Issue by vi-kumar** [zhanglonghao1992/One-Shot_Free-View_Neural_Talking_Head_Synthesis#9]
It would be great if you could let me know about the ground truth of tx, ty, tz? Authors have not talked much about t and delta

**Comment by zhanglonghao1992** [comment]
T and delta are optimized in a self-supervised way. There is no ground truth during training.

**Comment by vi-kumar** [comment]
Ohh, I will check it. Thank you for replying. Even I was implementing the paper :)
